swagger: 2.0
info:
  version: 0.1.0
  title: Rails Endpoint Definition
  description: This file is a Swagger Definition (Open API 2.0).
  license:
    name: MIT
basePath: /v0
host: localhost:3000
tags:
- name: user
  description: CRUD operation about users.
schemes:
- http
paths:
  "/users":
    post:
      tags:
      - user
      summary: Add a new user.
      operationId: createUser
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        description: User object to be added.
        required: true
        schema:
          "$ref": "#/definitions/User"
      responses:
        200:
          description: successful operation
          schema:
            "$ref": "#/definitions/User"
        400:
          description: bad request
  "/users/{user_id}":
    get:
      tags:
      - user
      summary: Get a user.
      operationId: getUser
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: user_id
        in: path
        description: User ID to be get.
        required: true
        type: integer
        example: 100
      responses:
        200:
          description: successful operation
          schema:
            "$ref": "#/definitions/UserWithGroups"
        400:
          description: bad request
        404:
          description: resource not found
    put:
      tags:
      - user
      summary: Update a user.
      operationId: updateUser
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: user_id
        in: path
        description: User ID to be updated.
        required: true
        type: integer
        example: 100
      - name: body
        in: body
        description: User object to be added.
        required: true
        schema:
          "$ref": "#/definitions/User"
      responses:
        200:
          description: successful operation
          schema:
            "$ref": "#/definitions/UserWithGroups"
        400:
          description: bad request
        404:
          description: resource not found
    delete:
      tags:
      - user
      summary: Delete a user.
      operationId: deleteUser
      deprecated: true
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: user_id
        in: path
        description: User ID to be deleted.
        required: true
        type: integer
        example: 100
      responses:
        200:
          description: successful operation
          schema:
            "$ref": "#/definitions/UserWithGroups"
        400:
          description: bad request
        404:
          description: resource not found
##
# -- Schema definitions
##
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 100
      name:
        type: string
        example: hoge
      email:
        type: string
        format: email
        example: example@hoge.com
  Group:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 100
      group_type:
        type: string
        example: hoge
  UserWithGroups:
    type: object
    properties:
      user:
        type: object
        $ref: "#/definitions/User"
      groups:
        type: array
        items:
          $ref: "#/definitions/Group"
