default: &default
  adapter: mysql2
  encoding: unicode
  pool: <%= ENV['RAILS_MAX_THREADS'] { 5 } %>
  host: <%= ENV['DATABASE_HOST'] { 'localhost' } %>
  username: <%= ENV['DATABASE_USERNAME'] { 'root' } %>
  password: <%= ENV['DATABASE_PASSWORD'] { 'password' } %>

development:
  <<: *default
  database: rails_api_development

test:
  <<: *default
  database: rails_api_test

production:
  <<: *default
  database: rails_api_production
  username: rails_api
  password: <%= ENV['RAILS_API_DATABASE_PASSWORD'] %>